apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
 name: local-disks
 namespace: local-storage
spec:
 logLevel: Normal
 managementState: Managed
 nodeSelector:
   nodeSelectorTerms:
   - matchExpressions:
     - key: kubernetes.io/hostname
       operator: In
       values:
       - worker-0
       - worker-1
       - worker-2
       - worker-3
       - worker-4
       - worker-5
       - worker-6
       - worker-7
 storageClassDevices:
 - devicePaths:
   - /dev/nvme0n1
   - /dev/nvme1n1
   - /dev/nvme2n1
   - /dev/nvme3n1
   storageClassName: localblock-sc
   volumeMode: Block
